apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: harbor
spec:
 storageClassName: "efs-sc"
 capacity:
   storage: 5Gi
 accessModes:
 - ReadWriteOnce
 hostPath:
   path: "/mnt/data/postgres"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: harbor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: "efs-sc"
  volumeName: postgres-pv

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: harbor
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: harbor
type: Opaque
data:
  postgres-password: ZXhhbXBsZXBhc3M=  # Base64 encoded password, change accordingly


---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: harbor
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14  # Specify the version of PostgreSQL you want to use
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              value: "exampledb"  # Database name
            - name: POSTGRES_USER
              value: "exampleuser"  # Database user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret  # Name of the secret that contains the password
                  key: postgres-password  # Key in the secret data
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data  # Mount path for PostgreSQL data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
